CREATE TABLE IF NOT EXISTS products (
    pid INT NOT NULL PRIMARY KEY,
    brand VARCHAR(50) CHARACTER SET utf8 NOT NULL,
    name VARCHAR(200) CHARACTER SET utf8 NOT NULL,
    model_no VARCHAR(50) CHARACTER SET utf8 NOT NULL,
    quantity INT NOT NULL,
    warranty_status VARCHAR(5) CHARACTER SET utf8 NOT NULL,
    on_sale TINYINT(1) DEFAULT 0,
    description VARCHAR(50) CHARACTER SET utf8 NOT NULL,
    distributor VARCHAR(50) CHARACTER SET utf8 NOT NULL,
    price_usd VARCHAR(20) CHARACTER SET utf8 NOT NULL,
    price_raw INT NOT NULL
    );
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000001, 'AEROCOOL', 'Aerocool 400W VX Series Active PFC Power Supply (AE-VX400)', 'AE-VX400', 81, '2yr', 'Aerocool Desktop Power Supply/PSU', 'Akortek', '25,71$ + Tax', 21);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000002, 'AEROCOOL', 'Aerocool 650W 80+ GOLD KCAS Series RGB Power Supply (AE-KCAS650G)', 'AE-KCAS650G', 73, '2yr', 'Aerocool Desktop Power Supply/PSU', 'Akortek', '77,12$ + Tax', 72);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000003, 'AEROCOOL', 'Aerocool 750W 80+ GOLD KCAS Series Half Modular RGB Power Supply (AE-KCAS750GM)', 'AE-KCAS750GM', 75, '2yr', 'Aerocool Desktop Power Supply/PSU', 'Akortek', '115,00$ + Tax', 95);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000004, 'AEROCOOL', 'Aerocool P7 750W 80+ Platinum RGB Led Modular Power Supply (AE-P7P750)', 'AE-P7P750', 61, '2yr', 'Aerocool Desktop Power Supply/PSU', 'Akortek', '178,66$ + Tax', 159);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000006, 'CORSAIR', 'Corsair 550W 80+ VS550 ATX Power Supply (CP-9020097-EU)', 'CP-9020097-EU', 89, '2yr', 'Corsair Desktop Power Supply/PSU', 'Vektron', '67,60$ + Tax', 56);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000007, 'CORSAIR', 'Corsair 650W 80+ Bronze CX650M Half Modular Power Supply (CP-9020103-EU)', 'CP-9020103-EU', 64, '2yr', 'Corsair Desktop Power Supply/PSU', 'Vektron', '110,50$ + Tax', 103);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000008, 'CORSAIR', 'Corsair 650W 80+ VS650 ATX Power Supply (CP-9020098-EU)', 'CP-9020098-EU', 56, '2yr', 'Corsair Desktop Power Supply/PSU', 'Vektron', '81,90$ + Tax', 68);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000009, 'CORSAIR', 'Corsair 750W 80+ Bronze CX750M ATX Power Supply (CP-9020061-EU)', 'CP-9020061-EU', 69, '2yr', 'Corsair Desktop Power Supply/PSU', 'Vektron', '171,60$ + Tax', 144);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000011, 'DARK', 'Dark 400W Dark Force ATX Power Supply (DKPS400S1)', 'DKPS400S1', 98, '2yr', 'Dark Desktop Power Supply/PSU', 'Akortek', '25,00$ + Tax', 21);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000012, 'DARK', 'Dark 600W Dark Force ATX Power Supply (DKPS600S1)', 'DKPS600S1', 54, '2yr', 'Dark Desktop Power Supply/PSU', 'Akortek', '37,50$ + Tax', 30);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000014, 'FSP', 'Fsp 500W 80+ Active PFC Power Supply (500-60AHBC)', '500-60AHBC', 57, '2yr', 'Fsp Desktop Power Supply/PSU', 'Segment Bilgisayar', '49,00$ + Tax', 41);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000016, 'HIGH POWER', 'High Power Power 400W ECO Active PFC High Efficiency Power Supply (HPE-400-A12S)', 'HPE-400-A12S', 85, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '23,90$ + Tax', 19);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000017, 'HIGH POWER', 'High Power Power 500W ECO Active PFC High Efficiency Power Supply (HPE-500-A12S)', 'HPE-500-A12S', 84, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '31,50$ + Tax', 25);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000018, 'HIGH POWER', 'High Power Power 1200W "Mining Edition" 80+ GOLD Astro GD Series Full Modular Power Supply (HPJ-1200GD-F14B)', 'HPJ-1200GD-F14B', 62, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '239,00$ + Tax', 210);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000019, 'HIGH POWER', 'High Power Power 350W 80+ Bronze SFX 8cm Fan Power Supply (HPF-350BR-H08S)', 'HPF-350BR-H08S', 63, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '45,00$ + Tax', 37);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000020, 'HIGH POWER', 'High Power Power 500W 80+ Bronze Red Active PFC Power Supply (HPE-500BR-A12S)', 'HPE-500BR-A12S', 70, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '40,23$ + Tax', 35);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000021, 'HIGH POWER', 'High Power Power 600W 80+ Bronze Element Bronze II Power Supply (HPG-600BR-H12S)', 'HPG-600BR-H12S', 68, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '59,50$ + Tax', 51);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000022, 'HIGH POWER', 'High Power Power 700W Simplicity 80+ Red Led Power Supply (HPG-700ST-T12S)', 'HPG-700ST-T12S', 59, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '62,00$ + Tax', 55);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000023, 'HIGH POWER', 'High Power Power 750W 80+ Bronze 56A@12V Power Supply (HPG-750BR-H12S)', 'HPG-750BR-H12S', 52, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '85,00$ + Tax', 72);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000024, 'HIGH POWER', 'High Power Power 750W 80+ Bronze Element Smart Blue Led 56A@12V Power Supply (HP-EP-750S)', 'HP-EP-750S', 52, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '83,90$ + Tax', 72);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000025, 'HIGH POWER', 'High Power Power 750W 80+ Gold 14cm Full Modular Power Supply (HPS-750GD-F14C)', 'HPS-750GD-F14C', 84, '2yr', 'High Power Desktop Power Supply/PSU', 'Akortek', '130,00$ + Tax', 114);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000027, 'SEASONIC', 'Seasonic 620W 80+ Bronze S12II Power Supply (SEA-S12II-620)', 'SEA-S12II-620', 83, '2yr', 'Seasonic Desktop Power Supply/PSU', 'Akortek', '92,00$ + Tax', 85);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000028, 'SEASONIC', 'Seasonic FOCUS PLUS 650W 80+ Gold Full Modular Power Supply (SSR-650FX)', 'SSR-650FX', 80, '2yr', 'Seasonic Desktop Power Supply/PSU', 'Akortek', '137,00$ + Tax', 130);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000029, 'SEASONIC', 'Seasonic FOCUS PLUS 750W 80+ Gold Full Modular Power Supply (SSR-750FX)', 'SSR-750FX', 98, '2yr', 'Seasonic Desktop Power Supply/PSU', 'Akortek', '184,00$ + Tax', 158);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000030, 'SEASONIC', 'Seasonic PRIME 1000W 80+ Platinum Full Modular Power Supply (SSR-1000PD)', 'SSR-1000PD', 64, '2yr', 'Seasonic Desktop Power Supply/PSU', 'Akortek', '289,00$ + Tax', 242);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000031, 'SEASONIC', 'Seasonic PRIME 1300W 80+ GOLD Full Modular Power Supply (SSR-1300GD)', 'SSR-1300GD', 60, '2yr', 'Seasonic Desktop Power Supply/PSU', 'Akortek', '319,00$ + Tax', 283);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000032, 'SEASONIC', 'Seasonic PRIME 1300W 80+ Platinum Full Modular Power Supply (SSR-1300PD)', 'SSR-1300PD', 57, '2yr', 'Seasonic Desktop Power Supply/PSU', 'Akortek', '345,00$ + Tax', 296);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000033, 'SEASONIC', 'Seasonic PRIME 750W 80+ Platinum Full Modular Power Supply (SSR-750PD)', 'SSR-750PD', 93, '2yr', 'Seasonic Desktop Power Supply/PSU', 'Akortek', '214,00$ + Tax', 194);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000034, 'SEASONIC', 'Seasonic PRIME 850W 80+ Platinum Full Modular Power Supply (SSR-850PD)', 'SSR-850PD', 95, '2yr', 'Seasonic Desktop Power Supply/PSU', 'Akortek', '247,00$ + Tax', 207);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000036, 'SILVERSTONE', 'Silverstone 1500W 80+ GOLD Strider Gold S Full Modular Power Supply (SST-ST1500-GS)', 'SST-ST1500-GS', 68, '2yr', 'Silverstone Desktop Power Supply/PSU', 'Akortek', '379,00$ + Tax', 306);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000037, 'SILVERSTONE', 'Silverstone 450W 80+ Bronze SFX Power Supply (SST-ST45SF)', 'SST-ST45SF', 73, '2yr', 'Silverstone Desktop Power Supply/PSU', 'Akortek', '97,00$ + Tax', 83);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000038, 'SILVERSTONE', 'Silverstone 500W Gemini 80+ Silver PS2 Mini Redundant Power Supply One 12V Channel, 40A Current - 500W x 2 (SST-ST50GF)', 'SST-ST50GF', 96, '2yr', 'Silverstone Desktop Power Supply/PSU', 'Akortek', '339,00$ + Tax', 288);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000039, 'SILVERSTONE', 'Silverstone 520W 80+ Platinum Nightjar Full Modular Power Supply (SST-NJ520)', 'SST-NJ520', 96, '2yr', 'Silverstone Desktop Power Supply/PSU', 'Akortek', '184,00$ + Tax', 172);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000040, 'SILVERSTONE', 'Silverstone 600W 80+ GOLD SFX Full Modular Power Supply (SST-SX600-G)', 'SST-SX600-G', 85, '2yr', 'Silverstone Desktop Power Supply/PSU', 'Akortek', '159,00$ + Tax', 151);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000041, 'SILVERSTONE', 'Silverstone 700W 80+ Bronze Strider Plus Full Modular Power Supply (SST-ST70F-PB)', 'SST-ST70F-PB', 92, '2yr', 'Silverstone Desktop Power Supply/PSU', 'Akortek', '100,00$ + Tax', 81);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000042, 'SILVERSTONE', 'Silverstone 750W 80+ Platinum Strider Full Modular Power Supply (SST-ST75F-PT)', 'SST-ST75F-PT', 52, '2yr', 'Silverstone Desktop Power Supply/PSU', 'Akortek', '184,00$ + Tax', 165);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000043, 'SILVERSTONE', 'Silverstone Strider Platinum 1200W 80+Platinum Full Modular Power Supply (SST-ST1200-PT)', 'SST-ST1200-PT', 61, '2yr', 'Silverstone Desktop Power Supply/PSU', 'Akortek', '319,00$ + Tax', 287);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000045, 'TX', 'Tx PowerMAX 250W 2xSATA, 2xIDE Power Supply (TXPSU250S1)', 'TXPSU250S1', 75, '2yr', 'Tx Desktop Power Supply/PSU', 'Akortek', '9,55$ + Tax', 7);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000046, 'TX', 'Tx PowerMAX 300W 2xSATA, 2xIDE, 4pin CPU Power Supply (TXPSU300C2)', 'TXPSU300C2', 82, '2yr', 'Tx Desktop Power Supply/PSU', 'Akortek', '12,20$ + Tax', 11);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000047, 'TX', 'Tx PowerMAX 300W 2xSATA, 2xIDE, 4pin CPU Power Supply (TXPSU300C1)', 'TXPSU300C1', 55, '2yr', 'Tx Desktop Power Supply/PSU', 'Akortek', '13,50$ + Tax', 12);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000048, 'TX', 'Tx PowerMAX 350W 2xSATA, 2xIDE, 8Pin CPU Power Supply (TXPSU350S1)', 'TXPSU350S1', 63, '2yr', 'Tx Desktop Power Supply/PSU', 'Akortek', '17,00$ + Tax', 14);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000049, 'TX', 'Tx PowerMAX 400W 3xSATA, 2xIDE, 8pin CPU, 6Pin PCI-E Power Supply (TXPSU400C1)', 'TXPSU400C1', 93, '2yr', 'Tx Desktop Power Supply/PSU', 'Akortek', '21,60$ + Tax', 19);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000050, 'TX', 'Tx PowerMAX 450W 3xSATA, 3xIDE, 8Pin CPU, PCI-E Power Supply (TXPSU450S1)', 'TXPSU450S1', 100, '2yr', 'Tx Desktop Power Supply/PSU', 'Akortek', '24,50$ + Tax', 23);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000052, 'THERMALTAKE', 'Thermaltake Litepower Black Edition 500W 120mm ATX Power Supply - (LT-500PCEU-A)', 'LT-500PCEU-A', 97, '2yr', 'Thermaltake Desktop Power Supply/PSU', 'Vektron', '56,00$ + Tax', 45);
INSERT INTO products (pid, brand, name, model_no, quantity, warranty_status, description, distributor, price_usd, price_raw) VALUES (17000053, 'THERMALTAKE', 'Thermaltake Toughpower 600W 80+ ATX 14cm Fan Power Supply - (W0103R)', 'W0103R', 98, '2yr', 'Thermaltake Desktop Power Supply/PSU', 'Vektron', '122,90$ + Tax', 109);
